### PR TITLE
Update impacket-0.9.12-r1.ebuild

### PR DESCRIPTION
**Pull request by necrose99**

### CODE REVIEW

**Comment by mudler** [comment]
Can you manifest it and put in one commit?

**Comment by necrose99** [comment]
<eroen> +necrose99: so maybe SRC_URI="https://github.com/CoreSecurity/impacket/archive/impacket_${PV//./_}.tar.gz -> ${P}.tar.gz" would work for you

**Comment by necrose99** [comment]
fixing URI to match,

**Comment by necrose99** [comment]
merge into my own repo will pull,

**Pull request closed without merging**
